airmozilla/suggest/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.start, name='start'),
    url(r'^autocomplete-emails/', views.autocomplete_emails,
        name='autocomplete_emails'),
    url(r'^(?P<id>\d+)/title/$', views.title, name='title'),
    url(r'^(?P<id>\d+)/file/$', views.choose_file, name='file'),
    url(r'^(?P<id>\d+)/popcorn/$', views.popcorn, name='popcorn'),
    url(r'^(?P<id>\d+)/description/$', views.description, name='description'),
    url(r'^(?P<id>\d+)/details/$', views.details, name='details'),
    url(r'^(?P<id>\d+)/discussion/$', views.discussion, name='discussion'),
    url(r'^(?P<id>\d+)/image/$', views.placeholder, name='placeholder'),
    url(r'^(?P<id>\d+)/summary/$', views.summary, name='summary'),
    url(r'^(?P<id>\d+)/delete/$', views.delete, name='delete'),
)

airmozilla/urls.py
from django.conf import settings
from django.conf.urls import patterns, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from funfactory.monkeypatches import patch
patch()


handler500 = 'airmozilla.base.views.handler500'


urlpatterns = patterns(
    '',
    (r'^(?P<path>contribute\.json)$', 'django.views.static.serve',
     {'document_root': settings.ROOT}),
    (r'^manage/', include('airmozilla.manage.urls', namespace='manage')),
    (r'^requests/', include('airmozilla.suggest.urls', namespace='suggest')),
    (r'^search/', include('airmozilla.search.urls', namespace='search')),
    (r'^comments/', include('airmozilla.comments.urls', namespace='comments')),
    (r'^surveys/', include('airmozilla.surveys.urls', namespace='surveys')),
    (r'^uploads/', include('airmozilla.uploads.urls', namespace='uploads')),
    (r'^roku/', include('airmozilla.roku.urls', namespace='roku')),
    (r'^mozillian/', include('airmozilla.webrtc.urls', namespace='webrtc')),
    ('^(?P<path>favicon\.ico)$', 'django.views.static.serve',
     {'document_root': settings.ROOT + '/airmozilla/base/static/img'}),
    (r'', include('django_browserid.urls')),
    (r'', include('airmozilla.main.urls', namespace='main')),
    ('^pages/', include('django.contrib.flatpages.urls')),
)

# In DEBUG mode, serve media files through Django.
if settings.DEBUG:  # pragma: no cover
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns(
        '',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT
        }),
    )
    urlpatterns += staticfiles_urlpatterns()

airmozilla/main/models.py
import datetime
import hashlib
import os
import unicodedata

from django.conf import settings
from django.contrib.auth.models import Group, User
from django.core.cache import cache
from django.db import models
from django.db.models import Q
from django.dispatch import receiver
from django.utils import timezone

from airmozilla.base.utils import unique_slugify
from airmozilla.main.fields import EnvironmentField
from airmozilla.manage.utils import filename_to_notes

import pytz
from sorl.thumbnail import ImageField


def _get_now():
    return timezone.now()


def _get_live_time():
    return (_get_now() +
            datetime.timedelta(minutes=settings.LIVE_MARGIN))


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    contributor = models.BooleanField(default=False)


@receiver(models.signals.post_save, sender=UserProfile)
@receiver(models.signals.post_save, sender=User)
def user_profile_clear_cache(sender, instance, **kwargs):
    if instance.__class__ is User:
        pk = instance.pk
    elif instance.__class__ is UserProfile:
        pk = instance.user.pk
    else:
        raise NotImplementedError
    cache.delete('is-contributor-%s' % pk)


def get_profile_safely(user, create_if_necessary=False):
    try:
        return user.profile
    except (UserProfile.DoesNotExist, AttributeError):
        # AttributeErrors happen if user is instance of AnonymousUser
        if create_if_necessary:
            return UserProfile.objects.create(user=user)


def _upload_path(tag):
    def _upload_path_tagged(instance, filename):
        if isinstance(filename, unicode):
            filename = (
                unicodedata
                .normalize('NFD', filename)
                .encode('ascii', 'ignore')
            )
        now = datetime.datetime.now()
        path = os.path.join(now.strftime('%Y'), now.strftime('%m'),
                            now.strftime('%d'))
        hashed_filename = (hashlib.md5(filename +
                           str(now.microsecond)).hexdigest())
        __, extension = os.path.splitext(filename)
        return os.path.join(tag, path, hashed_filename + extension)
    return _upload_path_tagged


class Channel(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True,
                            db_index=True)
    image = ImageField(upload_to=_upload_path('channels'), blank=True)
    image_is_banner = models.BooleanField(default=False)
    parent = models.ForeignKey('self', name='parent', null=True)
    description = models.TextField()
    created = models.DateTimeField(default=_get_now)
    reverse_order = models.BooleanField(default=False)
    exclude_from_trending = models.BooleanField(default=False)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def get_children(self):
        return Channel.objects.filter(parent=self)


class Tag(models.Model):
    """ Tags are flexible; events can have multiple tags. """
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name


class Template(models.Model):
    """Provides the HTML embed codes, links, etc. for each different type of
       video or stream."""
    name = models.CharField(max_length=100)
    content = models.TextField(
        help_text='The HTML framework for this template.  Use'
        ' <code>{{ any_variable_name }}</code> for per-event'
        ' tags. Other Jinja2 constructs are available, along with the related'
        ' <code>request</code>, <code>datetime</code>, <code>event</code> '
        ' objects, <code>popcorn_url</code> and the <code>md5</code> function.'
        ' You can also reference <code>autoplay</code> and it\'s always safe.'
        ' Additionally we have <code>vidly_tokenize(tag, seconds)</code> and'
        ' <code>edgecast_tokenize([seconds], **kwargs)</code>.<br>'
        ' Warning! Changes affect'
        ' all events associated with this template.'
    )
    default_popcorn_template = models.BooleanField(
        default=False,
        help_text='If you have more than one templates for Popcorn videos '
                  'this dictates which one is the default one.'
    )
    default_archive_template = models.BooleanField(
        default=False,
        help_text='When you archive an event, it needs to preselect which '
                  'template it should use. This selects the best default.'
    )

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Region(models.Model):
    """Region of a video/stream/presentation/etc."""
    name = models.CharField(max_length=300)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Location(models.Model):
    """Venue/location of a video/stream/presentation/etc."""
    name = models.CharField(max_length=300)
    timezone = models.CharField(max_length=250)
    is_active = models.BooleanField(default=True)
    regions = models.ManyToManyField(Region, blank=True)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name


class RecruitmentMessage(models.Model):
    text = models.CharField(max_length=250)
    url = models.URLField()
    active = models.BooleanField(default=True)
    notes = models.TextField(blank=True)

    modified_user = models.ForeignKey(User, null=True,
                                      on_delete=models.SET_NULL)
    created = models.DateTimeField(default=_get_now)
    modified = models.DateTimeField(auto_now=True, default=_get_now)

    class Meta:
        ordering = ['text']

    def __unicode__(self):
        return self.text


class EventManager(models.Manager):
    def initiated(self):
        return (self.get_query_set().filter(Q(status=Event.STATUS_INITIATED) |
                                            Q(approval__approved=False) |
                                            Q(approval__processed=False))
                    .distinct())

    def approved(self):
        return (self.get_query_set().exclude(approval__approved=False)
                    .exclude(approval__processed=False)
                    .filter(status=Event.STATUS_SCHEDULED))

    def upcoming(self):
        return self.approved().filter(
            archive_time=None,
            start_time__gt=_get_live_time()
        )

    def live(self):
        return self.approved().filter(
            archive_time=None,
            start_time__lt=_get_live_time()
        )

    def archiving(self):
        return self.approved().filter(
            archive_time__gt=_get_now(),
            start_time__lt=_get_live_time()
        )

    def archived(self):
        _now = _get_now()
        return self.approved().filter(
            archive_time__lt=_now,
            start_time__lt=_now
        )

    def archived_and_removed(self):
        _now = _get_now()
        return self.get_query_set().filter(
            (Q(archive_time__lt=_now, start_time__lt=_now)
             & ~Q(approval__approved=False)
             & ~Q(approval__processed=False)
             & Q(status=Event.STATUS_SCHEDULED))
            | Q(status=Event.STATUS_REMOVED)
        )


class Event(models.Model):
    """ Events - all the essential data and metadata for publishing. """
    title = models.CharField(max_length=200)
    slug = models.SlugField(blank=True, max_length=215, unique=True,
                            db_index=True)
    template = models.ForeignKey(Template, blank=True, null=True,
                                 on_delete=models.SET_NULL)
    template_environment = EnvironmentField(
        blank=True,
        help_text='Specify the template variables in the format'
        '<code>variable1=value</code>, one per line.'
    )
    STATUS_INITIATED = 'initiated'
    STATUS_SCHEDULED = 'scheduled'
    STATUS_PENDING = 'pending'
    STATUS_REMOVED = 'removed'
    STATUS_CHOICES = (
        (STATUS_INITIATED, 'Initiated'),
        (STATUS_SCHEDULED, 'Scheduled'),
        (STATUS_PENDING, 'Pending'),
        (STATUS_REMOVED, 'Removed')
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES,
                              default=STATUS_INITIATED, db_index=True)
    placeholder_img = ImageField(
        upload_to=_upload_path('event-placeholder'),
        blank=True,
        null=True,
    )
    picture = models.ForeignKey(
        'Picture',
        blank=True,
        null=True,
        related_name='event_picture',
        on_delete=models.SET_NULL
    )
    upload = models.ForeignKey(
        'uploads.Upload',
        null=True,
        related_name='event_upload',
        on_delete=models.SET_NULL
    )
    description = models.TextField()
    short_description = models.TextField(
        blank=True,
        help_text='If not provided, this will be filled in by the first '
        'words of the full description.'
    )
    start_time = models.DateTimeField(db_index=True)
    archive_time = models.DateTimeField(blank=True, null=True, db_index=True)
    location = models.ForeignKey(Location, blank=True, null=True,
                                 on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag, blank=True)
    channels = models.ManyToManyField(Channel)
    call_info = models.TextField(blank=True)
    additional_links = models.TextField(blank=True)
    remote_presenters = models.TextField(blank=True, null=True)

    popcorn_url = models.URLField(null=True, blank=True)

    PRIVACY_PUBLIC = 'public'
    PRIVACY_COMPANY = 'company'
    PRIVACY_CONTRIBUTORS = 'contributors'
    PRIVACY_CHOICES = (
        (PRIVACY_PUBLIC, 'Public'),
        (PRIVACY_CONTRIBUTORS, 'Contributors'),
        (PRIVACY_COMPANY, 'Staff'),
    )
    privacy = models.CharField(max_length=40, choices=PRIVACY_CHOICES,
                               default=PRIVACY_PUBLIC, db_index=True)

airmozilla/suggest/models.py
# deliberately empty

airmozilla/suggest/templates/suggest/_breadcrumb.html
<p class="breadcrumb" style="text-align: justify">
{% for link in suggest_breadcrumbs(event) %}
  <span class="node {% if link.url == request.path_info %}currently-on{% endif %}">
  {% if link.available %}
    <a href="{{ link.url }}">{{ link.description }}</a>
  {% else %}
    {{ link.description }}
  {% endif %}
  {% if not loop.last %}
    &rarr;
  {% endif %}
  </span>
{% endfor %}
</p>

airmozilla/suggest/templates/suggest/_default_form.html
{% include 'suggest/_alert_form_errors.html' %}
<form method="post" class="form-horizontal suggest">
    {{ csrf() }}
    {{ bootstrapform(form) }}

    {% if (event and not event.submitted) or not event %}
    {% include 'suggest/_form_buttons.html' %}
    {% elif event and event.submitted %}
    <em>Can't make changes to submitted requests</em>
    {% endif %}
</form>

airmozilla/suggest/templates/suggest/_default_form_upload.html
{% include 'suggest/_alert_form_errors.html' %}
<form method="post" enctype="multipart/form-data" class="form-horizontal suggest">
    {{ csrf() }}
    {{ bootstrapform(form) }}

    {% if event and not event.submitted %}
    {% include 'suggest/_form_buttons.html' %}
    {% endif %}
</form>

airmozilla/suggest/templates/suggest/_email_comment.html
{% extends "email_base.html" %}

{% block content %}

<p>
    A new comment has been posted on an existing event suggestion.
</p>

<table>
    <tr>
        <td><b>Comment:</b></td>
        <td>
            <i>{{ comment.comment }}</i>
        </td>
    </tr>
    <tr>
        <td><b>By:</b></td>
        <td>
            {% if comment.user.first_name %}
                {{ comment.user.first_name }}
                ({{ comment.user.email }})
            {% else %}
                {{ comment.user.email }}
            {% endif %}
        </td>
    </tr>
</table>


<p>
    To see all details go to the
    <a href="{{ base_url }}{{ url('suggest:summary', event.pk) }}">Summary page</a>.
</p>

<p>
{% if event.accepted %}
The event has already been accepted. To edit the event go to the
  <a href="{{ base_url}}{{ url('manage:event_edit', event.accepted.pk) }}">Event edit page</a>.
{% else %}
To review it and to turn it into a real event go to the
  <a href="{{ base_url }}{{ url('manage:suggestions') }}#s{{ event.pk }}">Event requests page</a>.
{% endif %}
</p>

<p>
    You are receiving this automated email because you have permission to add
    events on Air Mozilla.
</p>

{% endblock %}

airmozilla/suggest/templates/suggest/_form_buttons.html
<div class="form-actions">
    <button type="submit" class="btn btn-primary submit" name="submit">
      {%- if submit_text -%}
        {{ submit_text }}
      {%- else -%}
        Save and proceed
      {%- endif -%}
    </button>
    <!--<button class="btn cancel" name="cancel">Cancel</button>-->
</div>

airmozilla/suggest/templates/suggest/description.html
{% extends 'suggest/suggest_base.html' %}

{% block page_title %}
Event description | {{ super() }}
{% endblock %}

{% block content_main %}
  {% include 'suggest/_breadcrumb.html' %}

  <h2 class="section-title">Tell Us About Your Event</h2>

  {% include 'suggest/_default_form.html' %}


{% endblock %}

airmozilla/suggest/templates/suggest/details.html
{% extends 'suggest/suggest_base.html' %}

{% block page_title %}
Event details | {{ super() }}
{% endblock %}


{% block site_css %}
  {{ super() }}
  {% compress css %}
  <link href="{{ static('select2/select2.css') }}" rel="stylesheet" type="text/css">
  {% endcompress %}
  <link href="{{ static('suggest/jquery-ui/css/smoothness/jquery-ui-1.10.1.custom.min.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block site_js %}
  {{ super() }}
  <script src="{{ static('select2/select2.min.js') }}"></script>
  <script src="{{ static('suggest/jquery-ui/js/jquery-ui-1.10.1.custom.min.js') }}"></script>
  {% compress js %}
    <script src="{{ static('suggest/js/jquery-ui-timepicker-addon.js') }}"></script>
    <script src="{{ static('suggest/js/details.js') }}"></script>
  {% endcompress %}
{% endblock %}


{% block content_main %}
  {% include 'suggest/_breadcrumb.html' %}
  <h2 class="section-title">Event details</h2>

  {% include 'suggest/_default_form.html' %}

{% endblock %}

airmozilla/suggest/templates/suggest/discussion.html
{% extends 'suggest/suggest_base.html' %}

{% block page_title %}
Discussion Configuration | {{ super() }}
{% endblock %}

{% block site_css %}
  {{ super() }}
  {% compress css %}
  <link href="{{ static('select2/select2.css') }}" rel="stylesheet" type="text/css">
  {% endcompress %}
  <style>
  .disabled {
      opacity: 0.5;
  }
  </style>
{% endblock %}

{% block site_js %}
  {{ super() }}
  <script src="{{ static('select2/select2.min.js') }}"></script>
  {% compress js %}
  <script src="{{ static('suggest/js/discussion.js') }}"></script>
  {% endcompress %}
{% endblock %}

{% block content_main %}
  {% include 'suggest/_breadcrumb.html' %}
  <h2 class="section-title">Discussion Configuration</h2>


  {% include 'suggest/_default_form.html' %}


{% endblock %}

airmozilla/suggest/templates/suggest/file.html
{% extends 'suggest/suggest_base.html' %}

{% block page_title %}
Choose Uploaded File | {{ super() }}
{% endblock %}

{% block site_css %}
  {{ super() }}
  {% compress css %}
  <link href="{{ static('suggest/css/file.css') }}" rel="stylesheet" type="text/css">
  {% endcompress %}
{% endblock %}

{% block site_js %}
  {{ super() }}
  {% compress js %}
  <script src="{{ static('suggest/js/file.js') }}"></script>
  {% endcompress %}
{% endblock %}


{% block content_main %}
  {% include 'suggest/_breadcrumb.html' %}

  <h2 class="section-title">Choose Uploaded File</h2>

  {% include 'suggest/_default_form.html' %}

  <p>If you haven't already uploaded a file, <a href="{{ url('uploads:home') }}">go and do that now</a>.<br>
  You will automatically return to this page when you're done.
  </p>


{% endblock %}

airmozilla/suggest/templates/suggest/popcorn.html
{% extends 'suggest/suggest_base.html' %}

{% block page_title %}
Popcorn URL | {{ super() }}
{% endblock %}

{% block content_main %}
  {% include 'suggest/_breadcrumb.html' %}

  {% include 'suggest/_default_form.html' %}


{% endblock %}

airmozilla/suggest/templates/suggest/suggest_base.html
{% extends 'main/main_base.html' %}
{% set page='suggest' %}

{% block site_css %}
  {{ super() }}
  {% compress css %}
  <link href="{{ static('tooltipster/css/tooltipster.css') }}" rel="stylesheet" type="text/css">
  {% endcompress %}
  {% compress css %}
  <link href="{{ static('suggest/css/suggest.css') }}" rel="stylesheet" type="text/css">
  {% endcompress %}
{% endblock %}


{% block site_js %}
  {{ super() }}
  {% compress js %}
    <script src="{{ static('tooltipster/js/jquery.tooltipster.min.js') }}"></script>
  {% endcompress %}
  {% compress js %}
    <script src="{{ static('suggest/js/suggest.js') }}"></script>
  {% endcompress %}
{% endblock %}


{% block banner %}
    {% include 'main/_banner_small.html' %}
{% endblock %}

airmozilla/suggest/templates/suggest/summary.html
{% extends 'suggest/suggest_base.html' %}

{% block page_title %}
Event summary | {{ super() }}
{% endblock %}

{% block site_css %}
  {{ super() }}
  {% compress css %}
  <link href="{{ static('suggest/css/summary.css') }}" rel="stylesheet" type="text/css">
  {% endcompress %}
{% endblock %}

{% block content_main %}
  {% include 'suggest/_breadcrumb.html' %}
  <h2 class="section-title">Event summary</h2>

  {% if event.accepted %}
  <div class="accepted">
    <h3>Accepted!</h3>
    <p>
        {% if event.accepted.status == Event.STATUS_INITIATED %}
          This event has been accepted but not yet scheduled.
        {% elif event.accepted.status == Event.STATUS_SCHEDULED %}
          {% if event.accepted.needs_approval() %}
          This event has been accepted but is pending approval.
          {% else %}
          This event is
          <a href="{{ url('main:event', event.accepted.slug) }}">accepted and scheduled</a>.<br>
          {% if event.upcoming %}
            {% if event.start_time != event.accepted.start_time %}
              <b>Note!</b><br>
              The <b>scheduled time</b> is different from what you requested. The scheduled time is:
              <b>{{ event.accepted.location_time.strftime('%d %B %Y - %H:%M') }}</b>
              ({{ event.accepted.start_time|js_date }}).<br>
            {% endif %}
            {% if event.location != event.accepted.location %}
              <b>Note!</b><br>
              The <b>scheduled location</b> is different from what you requested. The scheduled location is:
              <b>{{ event.accepted.location.name }}</b>.
            {% endif %}
          {% endif %}

          {% endif %}
        {% elif event.accepted.status == Event.STATUS_REMOVED %}
          This event was accepted but was later removed.
        {% endif %}
    </p>
  </div>
  {% elif event.submitted %}
  <form action="" method="post" class="unsubmission">{{ csrf() }}
    <h3>Submitted!</h3>
    <p>This was submitted by <strong>{{ event.user.email }}</strong>
    <strong>{{ event.submitted|js_date }}</strong>.</p>

    {% if request.user == event.user %}
    <p>An Air Mozilla producer will review your event and either schedule
    it for broadcast or request additional information from you.</p>
    <button type="submit" class="btn btn-primary submit" name="unsubmit">Retract submission</button>
    {% else %}
    <p><a href="{{ url('manage:suggestions') }}#s{{ event.pk }}">Suggestions Management &raquo;</a></p>
    {% endif %}
  </form>
  {% else %}
  <div class="not-submitted">
    <h3>Almost there...</h3>
    {% if event.first_submitted %}
      <p>
        Your event is no longer submitted. It was either retracted or bounced back. See below for
        possible <b>review comments</b>. Submit again when it's ready.
      </p>
    {% else %}
      <p>
        Your event is not yet submitted. Check through the details and submit when you think you're ready.
      </p>
    {% endif %}
  </div>
  {% endif %}

  <table>
    {% if not event.submitted %}
    <tr>
      <td colspan="2" class="edit-link"><a href="{{ url('suggest:title', event.pk) }}">Change title</a></td>
    </tr>
    {% endif %}
    <tr>
      <th>Title</th>
      <td>{{ event.title }}</td>
    </tr>
    <tr>
      <th>Slug</th>
      <td>{{ event.slug }}</td>
    </tr>
    {% if event.popcorn_url %}
    {% if not event.submitted %}
    <tr>
      <td colspan="2" class="edit-link"><a href="{{ url('suggest:popcorn', event.pk) }}">Change Popcorn URL</a></td>
    </tr>
    {% endif %}

    <tr>
        <th>Popcorn URL</th>
        <td><a href="{{ event.popcorn_url }}" target="_blank">{{ truncate_url(event.popcorn_url, 70) }}</a></td>
    </tr>
    {% endif %}
    {% if not event.submitted %}
    <tr>
      <td colspan="2" class="edit-link"><a href="{{ url('suggest:description', event.pk) }}">Change description</a></td>
    </tr>
    {% endif %}
    <tr>
      <th>Description</th>
      <td>{{ event.description|urlize|nl2br }}</td>
    </tr>
    <tr>
      <th>Short description</th>
      <td>{{ event.short_description|urlize|nl2br }}</td>
    </tr>
    {% if not event.submitted %}
    <tr>
      <td colspan="2" class="edit-link"><a href="{{ url('suggest:details', event.pk) }}">Change details</a></td>
    </tr>
    {% endif %}
    {% if event.upcoming %}
    <tr>
      <th>Location</th>
      <td>
        {% if event.location %}
          {{ event.location }} ({{ event.location.timezone }})
        {% else %}
          <i>No location</i>
        {% endif %}
      </td>
    </tr>
    <tr>
      <th>Start time</th>
      <td>
        {% if event.location %}
          {{ event.location_time.strftime('%d %B %Y - %H:%M') }}
          ({{ event.start_time|js_date }})
        {% else %}
          {{ event.start_time|js_date }}
        {% endif %}
      </td>
    </tr>
    {% endif %}
    <tr>
      <th>Privacy</th>
      <td>{{ event.get_privacy_display() }}</td>
    </tr>
    <tr>
      <th>Tags</th>
      <td>{% for tag in event.tags.all() %}
      {{ tag }}{% if not loop.last %}, {% endif %}
      {% endfor %}
      </td>
    </tr>
    <tr>
      <th>Channels</th>
      <td>{% for channel in event.channels.all() %}
      {{ channel.name }}{% if not loop.last %}, {% endif %}
      {% endfor %}
      </td>
    </tr>
    <tr>
      <th>Additional links</th>
      <td>{{ event.additional_links|urlize|nl2br }}</td>
    </tr>
    {% if event.upcoming %}
    <tr>
      <th>Remote presenters</th>
      <td>
        {% if event.remote_presenters %}
          {{ event.remote_presenters|urlize|nl2br }}
        {% else %}
          none
        {% endif %}
      </td>
    </tr>
    {% endif %}

    {% if not event.submitted %}
    <tr>
      <td colspan="2" class="edit-link"><a href="{{ url('suggest:discussion', event.pk) }}">Change discussion</a></td>
    </tr>
    {% endif %}
    <tr>
        <th>Discussion</th>
        <td>
            {% if discussion and discussion.enabled %}
                <b>Enabled</b><br>
                {% if discussion.moderate_all %}
                All comments moderated.
                {% else %}
                Comments not moderated.
                {% endif %}
                <br>
                Email notifications sent to:
                {% for user in discussion.moderators.all() %}
                  {{ user.email }}{% if not loop.last %}, {% endif %}
                {% endfor %}
            {% else %}
            Not enabled
            {% endif %}
        </td>
    </tr>

    {% if not event.submitted %}
    <tr>
      <td colspan="2" class="edit-link"><a href="{{ url('suggest:placeholder', event.pk) }}">Change placeholder</a></td>
    </tr>
    {% endif %}
    <tr>
      <th>Placeholder picture</th>
      <td>
        {% if event.picture or event.placeholder_img %}
          {{ show_thumbnail(event, '160x90') }}
        {% else %}
          <p>No image!</p>
        {% endif %}
      </td>
    </tr>

    {% if event.submitted %}
    <tr>
      <th>Submitted</th>
      <td>{{ event.submitted|js_date }}</td>
    </tr>
    {% endif %}
    {% if event.review_comments %}
    <tr>
      <th>Review comments</th>
      <td>
        <div class="comment-text">{{ event.review_comments|urlize|nl2br }}</div>
      </td>
    </tr>
    {% endif %}

    <tr>
      <th>Additional comments</th>
      <td>
        {% for comment in comments %}
        <div class="comment">
          <div class="comment-text">{{ comment.comment|urlize|nl2br }}</div>
          <p>By
            {% if comment.user == request.user %}
              You
            {% else %}
              {{ comment.user.email }}
            {% endif %}
            -
            {{ comment.created|js_date }}
          </p>
        </div>
        {% endfor %}
        <form action="" method="post" class="comment">{{ csrf() }}
        {{ bootstrapform(comment_form) }}
        <div>
          <button type="submit" class="btn btn-primary submit" value="Comment" name="save_comment">Comment</button>
        </div>

        </form>
      </td>
    </tr>
  </table>


  {% if not event.submitted %}
  <form action="" method="post" class="submission">{{ csrf() }}
    <h3>Is it ready?</h3>
    <button type="submit" class="btn btn-primary submit" name="submit">Submit for review</button>
  </form>
  {% endif %}

{% endblock %}